name: pedidos-almuerzo

include:
  - path: ./supabase-docker/docker-compose.yml

services:
  frontend:
    image: 348847601284.dkr.ecr.us-east-1.amazonaws.com/pedidos-almuerzo-frontend:latest
    build:
      context: ./frontend
    container_name: pedidos-almuerzo-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
